

services:
  
  # Databases
  
  postgres:
    image: postgres:15
    container_name: yc_postgres
    environment:
      POSTGRES_USER: yc_user
      POSTGRES_PASSWORD: yc_pass
      POSTGRES_DB: yieldcraft
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: yc_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  
  # Backend API
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yc_backend
    depends_on:
      - postgres
      - mongodb
    environment:
      - DATABASE_URL=postgresql://yc_user:yc_pass@postgres:5432/yieldcraft
      - MONGO_URL=mongodb://yc_mongo:27017/yieldcraft
    ports:
      - "5000:5000"
    restart: always

  
  # Frontend (Angular)
  
  frontend:
    build:
      context: ./frontend/yieldcraft-ui
      dockerfile: Dockerfile
    container_name: yc_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always

  
  # Airflow (optional orchestration)
  
  airflow:
    image: apache/airflow:2.10.2
    container_name: yc_airflow
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=yourfernetkey
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
  mongodata:
